development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: salor_hospitality_development
  username: root
  password: root
  pool: 5
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: salor_hospitality_test
  username: root
  password: root
  pool: 5
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: salor_hospitality_production
  username: root
  password: root
  pool: 5
  host: localhost